version: "3.9"
services: 
        rdatos:
            image: docker_datos:4.0.5
            container_name: rdatos
            build:
                context: .
                dockerfile: ./dockerfiles/R4.0.5/Dockerfile
            restart: always
            environment:
                -root: "TRUE"
            env_file: .env
            ports: 
                - 20001:8787
                - 20000:3838
            volumes:
                - 'C:\Users\pablo.lopez\OneDrive - Izertis\Documentos\Proyectos\EDP\Cosmos\R_Analysis:/home/pablo.lopez'








